### ISSUE TITLE
Hey its Tango hotel here
I've been playing your work sfp in arma 3 . I have to say the effort was good.
But it's my humble request to fix these issues in swedish force pack in arma 3:-
1.when I was firing from the fh77 howitzer it was not stable I mean the gun after the firing shell at low angle (angle<40) is moving back side due to the impact . Make fh77 howitzer fire at low angle I mean (angles <40)
2.you have bought fh77a howitzer 39 caliber appreciable but I want you to bring fh77b howitzer 45 caliber .
3.important:-and make fh77b and fh77a towable. So that we can tow fh77a/b in game (without ace 3, alive support ).

### ISSUE THREAD

**Issue by kshitij132** [Anrop/Anrop-CBA-Settings#41]

**Comment by kshitij132** [comment]
Hey its Tango hotel here I've been playing your work sfp in arma 3 . I have to say the effort was good. But it's my humble request to fix these issues in swedish force pack in arma 3:- 1.when I was firing from the fh77 howitzer it was not stable I mean the gun after the firing shell at low angle (angle<40) is moving back side due to the impact . Make fh77 howitzer fire at low angle I mean (angles <40) 2.you have bought fh77a howitzer 39 caliber appreciable but I want you to bring fh77b howitzer 45 caliber . 3.important:-and make fh77b and fh77a towable. So that we can tow fh77a/b in game (without ace 3, alive support ).

**Comment by Dahlgren** [comment]
This repo contains Anrop's settings for CBA and is not related to SFP.
